= The Horror

:hp-alt-title: Der Horror
:published_at: 2015-11-11
:hp-tags: Fight, Life, The Horror, Der Horror, The Beginning, Der Anfang, My only friend - the end,

==== A place to say some things
I am creating this place on the internet to share some thoughts on the world in general, but also my life. These won't surely be politically correct in all cases, will be biased in many cases, will be very personal in some cases, always only reflect my own opinion (which tends to change frequently), and be certainly weird and nuts on many instances. Nobody has to listen, and nobody has to like it.
The title is inspired by Józef Teodor Nałęcz Konrad Korzeniowski's novel __Heart of Darkness__.

video::JSUIQgEVDM4[youtube]

==== Ein Ort um ein paar Sachen zu sagen
Diese Seite habe ich erstellt, um einfach ein paar Dinge zu sagen, die mir durch den Kopf schießen, über die Welt im generellen und mein Leben. Was hier steht wird zumeist nicht politisch korrekt sein, oder weise, oder klug, es wird immer subjektiv sein, es kann sehr persönlich sein, es gibt immer nur meine eigene Meinung wieder und es wird sicherlich of verrückt klingen. Niemand muss zuhören, und niemand muss es mögen.
Der Titel kommt aus Józef Teodor Nałęcz Konrad Korzeniowski Novelle __Herz der Finsternis__.

----
This is the end, beautiful friend 
This is the end, my only friend, the end 
Of our elaborate plans, the end 
Of everything that stands, the end 
No safety or surprise, the end 
I'll never look into your eyes, again 

Can you picture what will be, so limitless and free 
Desperately in need, of some, stranger's hand 
In a, desperate land 

Lost in a Roman wilderness of pain 
And all the children are insane, all the children are insane 
Waiting for the summer rain, yeah 
There's danger on the edge of town 
Ride the King's highway, baby 
Weird scenes inside the gold mine 
Ride the highway west, baby 
Ride the snake, ride the snake 
To the lake, the ancient lake, baby 
The snake is long, seven miles 

Ride the snake, he's old, and his skin is cold 
The west is the best, the west is the best 
Get here, and we'll do the rest 
The blue bus is callin' us, the blue bus is callin' us 
Driver, where you taken us 

The killer awoke before dawn, he put his boots on 
He took a face from the ancient gallery 
And he walked on down the hall 

He went into the room where his sister lived, and, then he 
Paid a visit to his brother, and then he 
He walked on down the hall, and 
And he came to a door, and he looked inside 
Father, yes son, I want to kill you 
Mother, I want to... 

C'mon baby, take a chance with us 
C'mon baby, take a chance with us 
C'mon baby, take a chance with us 

And meet me at the back of the blue bus 
Doin' a blue rock, on a blue bus 
Doin' a blue rock, c'mon, yeah 
Kill, kill, kill, kill, kill, kill 
This is the end, beautiful friend 

This is the end, my only friend, the end 
It hurts to set you free 
But you'll never follow me 
The end of laughter and soft lies 
The end of nights we tried to die 
This is the end
----
