
= A Story of Love: Background

:published_at: 2016-10-28
:hp-tags: Start, Beginning, TheLongStory, TrueNature, 

Here I am telling part of a story, part of a journey, my own journey. Then this is not quite correct a picture, because while it is a journey to fine my TrueNature, to being myself, it is also not a journey, because the essence of being in ones TrueNature is to be right here, right now, not moving, being nowhere else.
So, the picture of Joseph Conrads Into the Hearth of Darkness then is also an ambigous choice here. Or at least I am not on a journey up a river to find Mr. Kurtz, I am finding myself right in the hearth of darkness. Then again, darkness can be light, and what I am truly feeling into is the void and what comes from this.
In part this story then is about a love I found and lost. About love and pain. Unfortunately, the love I found, she won't even like this story to be told and thus I will keep many things in a way that she can't be identified or found. On the other hand, I would hope so much for her to understand, to come to this point where I am now, where I can accept, can feel the joy arising in my, the warmth and the smile on my face.
Why I am doing this? Well, it is good to tell a story and this is a real story of love and life. It is also who I am and what I am. In my hometown we would say I have always been carrying my heart on my tongue, I like to share my thoughts and feelings with my friend (and sometimes other people too). To long indeed have I been neglecting this side of mine and have been hiding, shielding myself. This is my process, my way....

